server:
  port: 9090

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    url: jdbc:oracle:thin:@//127.0.0.1:1521/xe
    hikari:
      username: sky
      password: java$!

  jpa:
    hibernate:
      ddl-auto: none # DDL 쿼리 자동 생성되지 않도록 설정(create:삭제후생성, update:변경된스키마적용)
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
        '[use_sql_comments]': true